# Use an official Python runtime as a parent image
FROM python:3.12.1-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . /usr/src/app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Define environment variables
ENV HOST_NEXT=127.0.0.1
ENV PORT_NEXT=12346
ENV LAYER=1

# Make port 12346 available to the world outside this container
EXPOSE 12346

# Run the Python script when the container launches
CMD ["python", "inferenceUE.py", "--host_next", "$HOST_NEXT", "--port_next", "$PORT_NEXT", "--add_lastlayer"]
